mysql:
  hostname: 127.0.0.1
  username: xxx
  password: 123456
  timeout: 1
  readtime: 2.3

default:
  driver: mysql
  hostname: localhost
  database: start
  username: root
  password: "123456"
  charset: utf8mb4
  collation: utf8mb4_unicode_ci
